-- Pulled from https://en.wikipedia.org/wiki/List_of_United_States_cities_by_population

insert into app_location (city, state) values('New York',' New York');
insert into app_location (city, state) values('Los Angeles',' California');
insert into app_location (city, state) values('Chicago',' Illinois');
insert into app_location (city, state) values('Houston',' Texas');
insert into app_location (city, state) values('Phoenix',' Arizona');
insert into app_location (city, state) values('Philadelphia',' Pennsylvania');
insert into app_location (city, state) values('San Antonio',' Texas');
insert into app_location (city, state) values('San Diego',' California');
insert into app_location (city, state) values('Dallas',' Texas');
insert into app_location (city, state) values('San Jose',' California');
insert into app_location (city, state) values('Austin',' Texas');
insert into app_location (city, state) values('Jacksonville',' Florida');
insert into app_location (city, state) values('San Francisco',' California');
insert into app_location (city, state) values('Columbus',' Ohio');
insert into app_location (city, state) values('Indianapolis',' Indiana');
insert into app_location (city, state) values('Fort Worth',' Texas');
insert into app_location (city, state) values('Charlotte',' North Carolina');
insert into app_location (city, state) values('Seattle',' Washington');
insert into app_location (city, state) values('Denver',' Colorado');
insert into app_location (city, state) values('El Paso',' Texas');
insert into app_location (city, state) values('Washington',' District of Columbia');
insert into app_location (city, state) values('Boston',' Massachusetts');
insert into app_location (city, state) values('Detroit',' Michigan');
insert into app_location (city, state) values('Nashville',' Tennessee');
insert into app_location (city, state) values('Memphis',' Tennessee');
insert into app_location (city, state) values('Portland',' Oregon');
insert into app_location (city, state) values('Oklahoma City',' Oklahoma');
insert into app_location (city, state) values('Las Vegas',' Nevada');
insert into app_location (city, state) values('Louisville',' Kentucky');
insert into app_location (city, state) values('Baltimore',' Maryland');
insert into app_location (city, state) values('Milwaukee',' Wisconsin');
insert into app_location (city, state) values('Albuquerque',' New Mexico');
insert into app_location (city, state) values('Tucson',' Arizona');
insert into app_location (city, state) values('Fresno',' California');
insert into app_location (city, state) values('Sacramento',' California');
insert into app_location (city, state) values('Mesa',' Arizona');
insert into app_location (city, state) values('Kansas City',' Missouri');
insert into app_location (city, state) values('Atlanta',' Georgia');
insert into app_location (city, state) values('Long Beach',' California');
insert into app_location (city, state) values('Colorado Springs',' Colorado');
insert into app_location (city, state) values('Raleigh',' North Carolina');
insert into app_location (city, state) values('Miami',' Florida');
insert into app_location (city, state) values('Virginia Beach',' Virginia');
insert into app_location (city, state) values('Omaha',' Nebraska');
insert into app_location (city, state) values('Oakland',' California');
insert into app_location (city, state) values('Minneapolis',' Minnesota');
insert into app_location (city, state) values('Tulsa',' Oklahoma');
insert into app_location (city, state) values('Arlington',' Texas');
insert into app_location (city, state) values('New Orleans',' Louisiana');
insert into app_location (city, state) values('Wichita',' Kansas');
insert into app_location (city, state) values('Cleveland',' Ohio');
insert into app_location (city, state) values('Tampa',' Florida');
insert into app_location (city, state) values('Bakersfield',' California');
insert into app_location (city, state) values('Aurora',' Colorado');
insert into app_location (city, state) values('Honolulu',' Hawaii');
insert into app_location (city, state) values('Anaheim',' California');
insert into app_location (city, state) values('Santa Ana',' California');
insert into app_location (city, state) values('Corpus Christi',' Texas');
insert into app_location (city, state) values('Riverside',' California');
insert into app_location (city, state) values('Lexington',' Kentucky');
insert into app_location (city, state) values('St. Louis',' Missouri');
insert into app_location (city, state) values('Stockton',' California');
insert into app_location (city, state) values('Pittsburgh',' Pennsylvania');
insert into app_location (city, state) values('Saint Paul',' Minnesota');
insert into app_location (city, state) values('Cincinnati',' Ohio');
insert into app_location (city, state) values('Anchorage',' Alaska');
insert into app_location (city, state) values('Henderson',' Nevada');
insert into app_location (city, state) values('Greensboro',' North Carolina');
insert into app_location (city, state) values('Plano',' Texas');
insert into app_location (city, state) values('Newark',' New Jersey');
insert into app_location (city, state) values('Lincoln',' Nebraska');
insert into app_location (city, state) values('Toledo',' Ohio');
insert into app_location (city, state) values('Orlando',' Florida');
insert into app_location (city, state) values('Chula Vista',' California');
insert into app_location (city, state) values('Irvine',' California');
insert into app_location (city, state) values('Fort Wayne',' Indiana');
insert into app_location (city, state) values('Jersey City',' New Jersey');
insert into app_location (city, state) values('Durham',' North Carolina');
insert into app_location (city, state) values('St. Petersburg',' Florida');
insert into app_location (city, state) values('Laredo',' Texas');
insert into app_location (city, state) values('Buffalo',' New York');
insert into app_location (city, state) values('Madison',' Wisconsin');
insert into app_location (city, state) values('Lubbock',' Texas');
insert into app_location (city, state) values('Chandler',' Arizona');
insert into app_location (city, state) values('Scottsdale',' Arizona');
insert into app_location (city, state) values('Glendale',' Arizona');
insert into app_location (city, state) values('Reno',' Nevada');
insert into app_location (city, state) values('Norfolk',' Virginia');
insert into app_location (city, state) values('Winston–Salem',' North Carolina');
insert into app_location (city, state) values('North Las Vegas',' Nevada');
insert into app_location (city, state) values('Irving',' Texas');
insert into app_location (city, state) values('Chesapeake',' Virginia');
insert into app_location (city, state) values('Gilbert',' Arizona');
insert into app_location (city, state) values('Hialeah',' Florida');
insert into app_location (city, state) values('Garland',' Texas');
insert into app_location (city, state) values('Fremont',' California');
insert into app_location (city, state) values('Baton Rouge',' Louisiana');
insert into app_location (city, state) values('Richmond',' Virginia');
insert into app_location (city, state) values('Boise',' Idaho');
insert into app_location (city, state) values('San Bernardino','Texas');
insert into app_location (city, state) values('Anchorage', 'Alaska');
